name: Tests

on:
    pull_request: null

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.3', '7.4', '8.0']
                path:
                    - tests
                    - rules-tests
                    - packages-tests

        name: PHP ${{ matrix.php }} tests in ${{ matrix.path }}
        steps:
            -   uses: actions/checkout@v2

            -
                uses: actions/cache@v2
                with:
                    path: tmp/rector/cache
                    key: ${{ runner.os }}-rector-kernel-${{ hashFiles('${{ matrix.path }}') }}
                    restore-keys: |
                        ${{ runner.os }}-rector-kernel-

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    # disable xdebug, pcov
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/phpunit ${{ matrix.path }}
